### ISSUE TITLE
common包需要安装吗?

### ISSUE THREAD

**Issue by brightgems** [huhu-jin/django_vue#2]
from common import utils
from common import validators as custom_validators
from common import models as custom_models
from common.models import CreateUpdateDateTimeModel
from common.models import CreateUpdateDeleteDateTimeModel
from common.models import EnabledObjectsManager
from common.models import NotDeletedObjectsManager
from common.model_fields import ListField

**Comment by huhu-jin** [comment]
修改了,以前项目的
